Feat/#132 청년 정책 상세 기능 구현 (#133)
* feat: 정책 분류 이미지 추가

* feat: analytics 리세팅

* feat: 화면 이벤트 적용

* feat: 키보드 높이 적용

* feat: 로깅 작업 완료

* refactor: 로깅 의존성 주입 방식 변경

EntryPoint 적용

* feat: 정책 상세 화면 이동기능 추가

* Revert "refactor: 로깅 의존성 주입 방식 변경"

This reverts commit 77275a3fb2c7d4048ad0f280fb5fa5b6a56e324b.

* feat: 정책 상세 데이터 작업

* feat: error 상태

 java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern

* fix: error 수정

* feat: 하이퍼링크 추가

* feat: title 애니메이션 적용

* feat: padding 수정

* feat: 로깅 작업